### ISSUE TITLE
Missing parameters for findoneandupdate

### ISSUE THREAD

**Issue by aoehmichen** [dsi-icl/borderline-utils#1]
https://github.com/dsi-icl/borderline-utils/blob/7323544a509701f6cd3245045624f7d5c333c2b4/src/registry.js#L123

You should define as well parameters w and j :

```
w | The write concern.
j |  Specify a journal write concern.

```
w should be set to "majority" and j to false. Majority ensure that the insertion is propagated to the majority of the cluster on insertion. j to false to avoid excess journaling.  http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html?_ga=2.262596236.1068064676.1509020505-1504984189.1509020505#insertOne

**Comment by fguitton** [comment]
The latest doc dosen't refer to these parameters at all :
http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#findOneAndUpdate
@aoehmichen Any comment or should I close this ?

**Comment by aoehmichen** [comment]
From what I have seen with driver 3, they have moved certain functions to other places like projection.

It is no longer an option in the find method but a method on its own that you append after the find...
